version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        tty: true
        command: sh -c "cargo prisma generate && cargo run --release"
        depends_on:
            - 'postgres'
        expose:
            - '3000'
