version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        command: sh -c "cargo prisma generate && cargo test"
        volumes:
            - .:/usr/src/app
        env_file:
            - .env
